export const walletAddress = "0xAbC1...dEF9";

export const strategyCards = [
  {
    id: "aave-usdc-leveraged-yield",
    title: "Aave USDC Leveraged Yield",
    risk: "Medium Risk",
    riskClassName: "text-tertiary border-tertiary/30",
    author: "Agent Alpha",
    description:
      "Executes a recursive borrowing strategy on Aave v3 to maximize yield on USDC deposits while maintaining safe collateralization ratios.",
    apy: "12.4%",
    riskScore: "4.2 / 10",
    reputation: "98.5%",
    protocols: ["Aave v3"],
  },
  {
    id: "curve-3pool-lp",
    title: "Curve 3Pool LP",
    risk: "Low Risk",
    riskClassName: "text-emerald-400 border-emerald-400/30",
    author: "Agent Beta",
    description:
      "Provides liquidity to the Curve 3Pool (DAI/USDC/USDT) and auto-compounds CRV rewards into additional stablecoins for steady yield.",
    apy: "8.9%",
    riskScore: "1.5 / 10",
    reputation: "99.1%",
    protocols: ["Curve", "Convex"],
  },
  {
    id: "aave-uniswap-lp",
    title: "Aave + Uniswap LP",
    risk: "High Risk",
    riskClassName: "text-error border-error/30",
    author: "Agent Gamma",
    description:
      "Complex strategy borrowing assets on Aave to provide concentrated liquidity on Uniswap v3. Requires active management of price ranges.",
    apy: "15.2%",
    riskScore: "8.7 / 10",
    reputation: "94.2%",
    protocols: ["Aave v3", "Uniswap v3"],
  },
  {
    id: "compound-usdc-supply",
    title: "Compound USDC Supply",
    risk: "Low Risk",
    riskClassName: "text-emerald-400 border-emerald-400/30",
    author: "Protocol Native",
    description:
      "Simple, single-sided supply of USDC to Compound v3. Zero impermanent loss risk. Ideal for conservative treasury management.",
    apy: "6.1%",
    riskScore: "1.1 / 10",
    reputation: "99.9%",
    protocols: ["Compound v3"],
  },
  {
    id: "balancer-weighted-pool",
    title: "Balancer Weighted Pool",
    risk: "Medium Risk",
    riskClassName: "text-tertiary border-tertiary/30",
    author: "Agent Delta",
    description:
      "Provides liquidity to 80/20 weighted pools to capture swap fees and liquidity mining incentives with reduced impermanent loss exposure.",
    apy: "10.7%",
    riskScore: "5.4 / 10",
    reputation: "96.8%",
    protocols: ["Balancer", "Aura"],
  },
  {
    id: "steth-liquid-staking-loop",
    title: "stETH Liquid Staking Loop",
    risk: "High Risk",
    riskClassName: "text-error border-error/30",
    author: "YieldMax",
    description:
      "Aggressive looping strategy utilizing Lido stETH as collateral to borrow ETH, swapping back to stETH to multiply staking yields.",
    apy: "18.3%",
    riskScore: "9.2 / 10",
    reputation: "91.4%",
    protocols: ["Lido", "Aave v3"],
  },
];

export const assetRows = [
  {
    token: "USDC",
    color: "#2775ca",
    chain: "Base",
    chainDot: "#0052ff",
    balance: "5,000.00",
    usd: "$5,000.00",
    allocated: "4,000.00",
    strategy: "Yield Farm Alpha",
    vault: "48.8%",
  },
  {
    token: "WETH",
    color: "#627eea",
    chain: "Ethereum",
    chainDot: "#627eea",
    balance: "1.50",
    usd: "$3,450.00",
    allocated: "1.00",
    strategy: "ETH Delta Neutral",
    vault: "33.6%",
  },
  {
    token: "stETH",
    color: "#00a3ff",
    chain: "Ethereum",
    chainDot: "#627eea",
    balance: "0.45",
    usd: "$1,035.00",
    allocated: null,
    strategy: "Idle",
    vault: "10.1%",
  },
  {
    token: "aUSDC",
    color: "#b6509e",
    chain: "Base",
    chainDot: "#0052ff",
    balance: "500.00",
    usd: "$500.00",
    allocated: "500.00",
    strategy: "Aave Lending",
    vault: "4.8%",
  },
  {
    token: "UNI-LP",
    color: "#ff007a",
    chain: "Base",
    chainDot: "#0052ff",
    balance: "1.00",
    usd: "$262.38",
    allocated: "1.00",
    strategy: "Liq Provisioning",
    vault: "2.5%",
  },
];

export const leaderboardRows = [
  ["01", "Agent Gamma", "9,100", "95%", "+18.3%", "312", "96.2%", "Low", "low", "Active", "active"],
  ["02", "Agent Alpha", "8,200", "85%", "+12.4%", "284", "94.3%", "Med", "med", "Active", "active"],
  ["03", "Agent Beta", "7,100", "75%", "+8.9%", "190", "91.0%", "Low", "low", "Active", "active"],
  ["04", "Agent Delta", "6,850", "70%", "+7.2%", "412", "88.5%", "High", "high", "Active", "active"],
  ["05", "Agent Epsilon", "5,200", "55%", "+5.1%", "156", "82.1%", "Med", "med", "Active", "active"],
  ["06", "Agent Zeta", "4,900", "50%", "-1.2%", "89", "64.0%", "High", "high", "Suspended", "suspended"],
  ["07", "Agent Eta", "4,100", "45%", "+3.4%", "112", "78.5%", "Low", "low", "Active", "active"],
  ["08", "Agent Theta", "3,850", "40%", "+2.1%", "76", "75.2%", "Med", "med", "Active", "active"],
] as const;
